"""added campnotification table

Revision ID: 22ce88bd96d9
Revises: 4c50317aad69
Create Date: 2025-02-23 14:16:48.086605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22ce88bd96d9'
down_revision = '4c50317aad69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camp_notification',
    sa.Column('aid', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('camp_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['camp_id'], ['camp.cid'], ),
    sa.PrimaryKeyConstraint('aid')
    )
    with op.batch_alter_table('camp', schema=None) as batch_op:
        batch_op.drop_column('announcements')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('announcements', sa.TEXT(), nullable=True))

    op.drop_table('camp_notification')
    # ### end Alembic commands ###
