"""initial

Revision ID: 3368c500b212
Revises: bc32261f2e75
Create Date: 2025-03-23 22:28:43.988809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3368c500b212'
down_revision = 'bc32261f2e75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camp_notification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'camp', ['camp_id'], ['cid'], ondelete='CASCADE')

    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['uid'], ondelete='SET NULL')

    with op.batch_alter_table('reply', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['uid'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'thread', ['thread_id'], ['tid'], ondelete='SET NULL')

    with op.batch_alter_table('thread', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['uid'], ondelete='SET NULL')

    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.drop_constraint('fk_volunteer_user', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['uid'], ondelete='SET NULL')

    with op.batch_alter_table('volunteer_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'camp', ['camp_id'], ['cid'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'volunteer', ['vid'], ['vid'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'camp', ['camp_id'], ['cid'])
        batch_op.create_foreign_key(None, 'volunteer', ['vid'], ['vid'])

    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_volunteer_user', 'user', ['user_id'], ['uid'])

    with op.batch_alter_table('thread', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['uid'])

    with op.batch_alter_table('reply', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'thread', ['thread_id'], ['tid'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['uid'])

    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['uid'])

    with op.batch_alter_table('camp_notification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'camp', ['camp_id'], ['cid'])

    # ### end Alembic commands ###
