"""modified volunteer histroy

Revision ID: 3a33eb3cd7c4
Revises: 763f6f772f83
Create Date: 2025-03-14 11:14:39.465575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a33eb3cd7c4'
down_revision = '763f6f772f83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vdate', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_history', schema=None) as batch_op:
        batch_op.drop_column('vdate')

    # ### end Alembic commands ###
