"""camp attribute update

Revision ID: 3e7adcecc0b6
Revises: 8a00f2663998
Create Date: 2025-03-24 11:03:32.517754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e7adcecc0b6'
down_revision = '8a00f2663998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('essentials_stock', sa.Integer(), nullable=True))
        batch_op.drop_column('essentiasl_stock')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('essentiasl_stock', sa.INTEGER(), nullable=True))
        batch_op.drop_column('essentials_stock')

    # ### end Alembic commands ###
