"""modified camp datatype for people list

Revision ID: 3edb81c8e617
Revises: c16739497281
Create Date: 2025-03-21 10:31:13.592759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3edb81c8e617'
down_revision = 'c16739497281'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camp', schema=None) as batch_op:
        batch_op.alter_column('people_list',
               existing_type=sa.BLOB(),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camp', schema=None) as batch_op:
        batch_op.alter_column('people_list',
               existing_type=sa.JSON(),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
