"""updated user to add volunteer history

Revision ID: 763f6f772f83
Revises: ed1e620e28a2
Create Date: 2025-03-14 10:08:56.704867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '763f6f772f83'
down_revision = 'ed1e620e28a2'
branch_labels = None
depends_on = None


def upgrade():
    # Add the new column with a temporary default value (e.g., 1)
    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('user_id', sa.Integer(), nullable=False, server_default="1")
        )
        batch_op.create_foreign_key('fk_volunteer_user', 'user', ['user_id'], ['uid'])
    
    # Remove the temporary default if it is not desired for future inserts
    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.alter_column('user_id', server_default=None)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
