"""no of people count

Revision ID: 770db8d05d9c
Revises: 3e7adcecc0b6
Create Date: 2025-03-24 11:16:49.218622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '770db8d05d9c'
down_revision = '3e7adcecc0b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camp', schema=None) as batch_op:
        batch_op.drop_column('num_people_present')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_people_present', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
