"""testing user log

Revision ID: 8773a2d6503a
Revises: ea2cc213084e
Create Date: 2025-03-23 22:03:40.365659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8773a2d6503a'
down_revision = 'ea2cc213084e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('user_activity',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('user_id', sa.Integer(), nullable=False),
    # sa.Column('action', sa.String(length=255), nullable=False),
    # sa.Column('timestamp', sa.DateTime(), nullable=False),
    # sa.ForeignKeyConstraint(['user_id'], ['user.uid'], ondelete='SET NULL'),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.drop_table('recent_activities')
    with op.batch_alter_table('camp_notification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'camp', ['camp_id'], ['cid'], ondelete='CASCADE')

    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['uid'], ondelete='SET NULL')

    with op.batch_alter_table('reply', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['uid'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'thread', ['thread_id'], ['tid'], ondelete='SET NULL')

    with op.batch_alter_table('thread', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['uid'], ondelete='SET NULL')

    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.drop_constraint('fk_volunteer_user', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['uid'], ondelete='SET NULL')

    with op.batch_alter_table('volunteer_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'volunteer', ['vid'], ['vid'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'camp', ['camp_id'], ['cid'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'volunteer', ['vid'], ['vid'])
        batch_op.create_foreign_key(None, 'camp', ['camp_id'], ['cid'])

    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_volunteer_user', 'user', ['user_id'], ['uid'])

    with op.batch_alter_table('thread', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['uid'])

    with op.batch_alter_table('reply', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['uid'])
        batch_op.create_foreign_key(None, 'thread', ['thread_id'], ['tid'])

    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['uid'])

    with op.batch_alter_table('camp_notification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'camp', ['camp_id'], ['cid'])

    # op.create_table('recent_activities',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('user_id', sa.INTEGER(), nullable=False),
    # sa.Column('action', sa.VARCHAR(length=255), nullable=False),
    # sa.Column('timestamp', sa.DATETIME(), nullable=False),
    # sa.ForeignKeyConstraint(['user_id'], ['user.uid'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.drop_table('user_activity')
    # ### end Alembic commands ###
