"""initial

Revision ID: 8a00f2663998
Revises: 
Create Date: 2025-03-24 10:54:55.778359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a00f2663998'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_capacity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('water_capacity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('essentials_capacity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('essentiasl_stock', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('clothes_capacity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('clothes_stock', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camp', schema=None) as batch_op:
        batch_op.drop_column('clothes_stock')
        batch_op.drop_column('clothes_capacity')
        batch_op.drop_column('essentiasl_stock')
        batch_op.drop_column('essentials_capacity')
        batch_op.drop_column('water_capacity')
        batch_op.drop_column('food_capacity')

    # ### end Alembic commands ###
