"""modified user model, added feedback model

Revision ID: 9487540efd38
Revises: 6ccd41a8657c
Create Date: 2025-03-10 10:31:14.411310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9487540efd38'
down_revision = '6ccd41a8657c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('fid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('fid')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('camp_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'camp', ['camp_id'], ['cid'])
        batch_op.drop_column('family_list')
        batch_op.drop_column('friend_list')
        batch_op.drop_column('associated_camp_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('associated_camp_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('friend_list', sa.BLOB(), nullable=True))
        batch_op.add_column(sa.Column('family_list', sa.BLOB(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'camp', ['associated_camp_id'], ['cid'])
        batch_op.drop_column('camp_id')

    op.drop_table('feedback')
    # ### end Alembic commands ###
