"""updated donation, added donationAmount

Revision ID: c16739497281
Revises: 53c3e5520501
Create Date: 2025-03-16 16:41:18.324799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c16739497281'
down_revision = '53c3e5520501'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donation_amount',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('user_id', 'amount_id')
    )
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.FLOAT(), nullable=True))

    op.drop_table('donation_amount')
    # ### end Alembic commands ###
