"""initial

Revision ID: c81f30cb3206
Revises: 3368c500b212
Create Date: 2025-03-23 22:29:35.887902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c81f30cb3206'
down_revision = '3368c500b212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camp_notification', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_camp_notification_camp_id', 'camp', ['camp_id'], ['cid'], ondelete='CASCADE')

    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_donation_user_id', 'user', ['user_id'], ['uid'], ondelete='SET NULL')

    with op.batch_alter_table('reply', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_reply_user_id', 'user', ['user_id'], ['uid'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_reply_thread_id', 'thread', ['thread_id'], ['tid'], ondelete='SET NULL')

    with op.batch_alter_table('thread', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_thread_user_id', 'user', ['user_id'], ['uid'], ondelete='SET NULL')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_user_associated_camp_id', 'camp', ['associated_camp_id'], ['cid'], ondelete='SET NULL')

    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.drop_constraint('fk_volunteer_user', type_='foreignkey')
        batch_op.create_foreign_key('fk_volunteer_user_id', 'user', ['user_id'], ['uid'], ondelete='SET NULL')

    with op.batch_alter_table('volunteer_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_volunteer_history_camp_cid', 'camp', ['camp_id'], ['cid'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_volunteer_history_volunteer_vid', 'volunteer', ['vid'], ['vid'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_history', schema=None) as batch_op:
        batch_op.drop_constraint('fk_volunteer_history_volunteer_vid', type_='foreignkey')
        batch_op.drop_constraint('fk_volunteer_history_camp_cid', type_='foreignkey')
        batch_op.create_foreign_key(None, 'volunteer', ['vid'], ['vid'])
        batch_op.create_foreign_key(None, 'camp', ['camp_id'], ['cid'])

    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.drop_constraint('fk_volunteer_user_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_volunteer_user', 'user', ['user_id'], ['uid'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_associated_camp_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'camp', ['associated_camp_id'], ['cid'])

    with op.batch_alter_table('thread', schema=None) as batch_op:
        batch_op.drop_constraint('fk_thread_user_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['uid'])

    with op.batch_alter_table('reply', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reply_thread_id', type_='foreignkey')
        batch_op.drop_constraint('fk_reply_user_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['uid'])
        batch_op.create_foreign_key(None, 'thread', ['thread_id'], ['tid'])

    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_constraint('fk_donation_user_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['uid'])

    with op.batch_alter_table('camp_notification', schema=None) as batch_op:
        batch_op.drop_constraint('fk_camp_notification_camp_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'camp', ['camp_id'], ['cid'])

    # ### end Alembic commands ###
