"""updated constraints in volunteer model

Revision ID: ed1e620e28a2
Revises: 37a239bb05f5
Create Date: 2025-03-12 14:27:49.568847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed1e620e28a2'
down_revision = '37a239bb05f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteer_history',
    sa.Column('vhid', sa.Integer(), nullable=False),
    sa.Column('vid', sa.Integer(), nullable=False),
    sa.Column('camp_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['camp_id'], ['camp.cid'], ),
    sa.ForeignKeyConstraint(['vid'], ['volunteer.vid'], ),
    sa.PrimaryKeyConstraint('vhid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volunteer_history')
    # ### end Alembic commands ###
