"""Add donations_received and donations_spent to Camp

Revision ID: fce3386cb631
Revises: 22ce88bd96d9
Create Date: 2025-02-23 14:53:12.155887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fce3386cb631'
down_revision = '22ce88bd96d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donations_received', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('donations_spent', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camp', schema=None) as batch_op:
        batch_op.drop_column('donations_spent')
        batch_op.drop_column('donations_received')

    # ### end Alembic commands ###
